openapi: 3.0.1
info:
  title: Emarket - Marketing HTTP API
  description: The Marketing Service HTTP API
  version: v1
servers:
  - url: /marketing-api
paths:
  /api/v1/campaigns:
    get:
      tags:
        - Campaigns
      operationId: "getCampaignList"      
      parameters:
        # pageSize=100&pageIndex=0
        - name: pageSize
          in: query
          required: false
          schema:
            type: integer
            example: 100
        - name: pageIndex
          in: query
          required: false
          schema:
            type: integer
            example: 0
      responses:
        '200':
          description: Success
          content:
            # text/plain:
            #   schema:
            #     type: array
            #     items:
            #       $ref: '#/components/schemas/CampaignDTO'
            #     nullable: true
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CampaignDTO'
                nullable: true
            # text/json:
            #   schema:
            #     type: array
            #     items:
            #       $ref: '#/components/schemas/CampaignDTO'
            #     nullable: true
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
        - accessToken:
            - secret

components:
  schemas:
    CampaignDTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 1
        name:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
        From:
          type: string
          format: date-time
        to:
          type: string
          format: date-time
        pictureUri:
          type: string
          nullable: true
        detailsUri:
          type: string
          nullable: true
      
  # securitySchemes:
  #   accessToken:
  #     type: http
  #     scheme: bearer
  #     bearerFormat: JWT
