openapi: 3.0.1
info:
  title: Emarket - Marketing HTTP API
  description: The Marketing Service HTTP API
  version: v1
servers:
  - url: /marketing-api
paths:
  /api/v1/campaigns:
    get:
      tags:
        - Campaigns
      operationId: "getCampaignList"            
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CampaignDTO'
                nullable: true        
  /api/v1/campaigns/{id}:
    get:
      tags:
        - Campaigns
      operationId: "getCampaign"      
      parameters: 
        - name: id
          in: path
          description: Campaign ID
          required: true
          schema:
            type: integer
            format: int32      
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CampaignDTO'
components:
  schemas:
    CampaignDTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 1
        name:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
        From:
          type: string
          format: date-time
        to:
          type: string
          format: date-time
        pictureUri:
          type: string
          nullable: true
        detailsUri:
          type: string
          nullable: true